#requires -Version 7.0
[CmdletBinding()]
param(
    [string]$Staging = (Join-Path $PSScriptRoot '../staging'),
    [string]$OutputDirectory = (Join-Path $PSScriptRoot '../dist'),
    [string]$MakeNsis = 'makensis.exe',
    [ValidatePattern('^$|^[A-Fa-f0-9]{40}$')]
    [string]$CertificateThumbprint = '',
    [string]$SignTool = 'signtool.exe',
    [ValidatePattern('^https?://[A-Za-z0-9./:_-]+$')]
    [string]$TimestampUrl = 'http://timestamp.digicert.com'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Invoke-CheckedNative {
    param([string]$Program, [string[]]$Arguments)
    & $Program @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "$Program failed with exit code $LASTEXITCODE."
    }
}

function Sign-ReleaseFile {
    param([string]$Path)
    Invoke-CheckedNative $script:SignTool @('sign', '/sha1', $CertificateThumbprint,
        '/fd', 'SHA256', '/tr', $TimestampUrl, '/td', 'SHA256', $Path)
    Invoke-CheckedNative $script:SignTool @('verify', '/pa', '/all', '/tw', $Path)
}

$stagePath = (Resolve-Path -LiteralPath $Staging).Path.TrimEnd('\')
$outputPath = [IO.Path]::GetFullPath($OutputDirectory).TrimEnd('\')
if ($outputPath.Equals($stagePath, [StringComparison]::OrdinalIgnoreCase) -or
    $outputPath.StartsWith($stagePath + '\', [StringComparison]::OrdinalIgnoreCase)) {
    throw 'OutputDirectory must be outside the staging directory.'
}

$MakeNsis = (Get-Command $MakeNsis -CommandType Application -ErrorAction Stop).Source
if ($CertificateThumbprint) {
    $SignTool = (Get-Command $SignTool -CommandType Application -ErrorAction Stop).Source
}
# These paths are also passed to the NSIS preprocessor and its signing command.
foreach ($path in @($stagePath, $outputPath, $PSScriptRoot, $SignTool)) {
    if ($path -match '[\r\n\x22\x27$%&|<>^]') {
        throw "Use a build path without shell/preprocessor metacharacters: $path"
    }
}
foreach ($file in @('OpenNord.exe', 'OpenNordService.exe', 'Qt6Core.dll',
    'Qt6Network.dll', 'Qt6Widgets.dll', 'platforms/qwindows.dll',
    'tls/qschannelbackend.dll', 'LICENSE', 'README.md', 'SECURITY.md')) {
    if (-not (Test-Path -LiteralPath (Join-Path $stagePath $file) -PathType Leaf)) {
        throw "Missing staged file: $file. Install and deploy the Release build first."
    }
}
if ((Get-Item -LiteralPath $stagePath).Attributes -band [IO.FileAttributes]::ReparsePoint) {
    throw 'Staging must be a regular directory, not a link.'
}
if (Get-ChildItem -LiteralPath $stagePath -Recurse -Force |
    Where-Object { $_.Attributes -band [IO.FileAttributes]::ReparsePoint }) {
    throw 'Staging must not contain links or junctions.'
}
if (Test-Path -LiteralPath (Join-Path $stagePath 'Uninstall.exe')) {
    throw 'Use a fresh staging directory, not an existing installation.'
}

New-Item -ItemType Directory -Path $outputPath -Force | Out-Null
if ($CertificateThumbprint) {
    Sign-ReleaseFile (Join-Path $stagePath 'OpenNord.exe')
    Sign-ReleaseFile (Join-Path $stagePath 'OpenNordService.exe')
} else {
    Write-Warning 'Creating unsigned development artifacts. Public releases should use a trusted signing certificate.'
}

# Hash the final payload after signing. Do not include a previous hash manifest.
$payloadHashes = @(Get-ChildItem -LiteralPath $stagePath -Recurse -File -Force |
    Where-Object { $_.FullName -ne (Join-Path $stagePath 'SHA256SUMS.txt') } |
    Sort-Object FullName | ForEach-Object {
        $relative = [IO.Path]::GetRelativePath($stagePath, $_.FullName).Replace('\', '/')
        '{0}  {1}' -f (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant(), $relative
    })
$payloadHashes | Set-Content -LiteralPath (Join-Path $stagePath 'SHA256SUMS.txt') -Encoding utf8NoBOM

# The uninstaller must never recursively delete an arbitrary directory chosen
# in setup. Compile an exact list from this package, then remove empty folders.
$packageWork = Join-Path $PSScriptRoot '../build/packaging'
New-Item -ItemType Directory -Path $packageWork -Force | Out-Null
$uninstallInclude = [IO.Path]::GetFullPath((Join-Path $packageWork 'uninstall-files.nsh'))
$uninstallLines = @('; Generated by Package-Windows.ps1; do not edit.')
$uninstallLines += @(Get-ChildItem -LiteralPath $stagePath -Recurse -File -Force |
    Sort-Object FullName | ForEach-Object {
        $relative = [IO.Path]::GetRelativePath($stagePath, $_.FullName).Replace('$', '$$')
        'Delete "$INSTDIR\' + $relative + '"'
    })
$uninstallLines += @(Get-ChildItem -LiteralPath $stagePath -Recurse -Directory -Force |
    Sort-Object { $_.FullName.Length } -Descending | ForEach-Object {
        $relative = [IO.Path]::GetRelativePath($stagePath, $_.FullName).Replace('$', '$$')
        'RMDir "$INSTDIR\' + $relative + '"'
    })
$uninstallLines | Set-Content -LiteralPath $uninstallInclude -Encoding utf8BOM

$installerPath = Join-Path $outputPath 'OpenNord-Setup.exe'
$nsisArguments = @('/V2', "/DSTAGING=$stagePath", "/DOUTPUT=$installerPath",
    "/DUNINSTALL_INCLUDE=$uninstallInclude")
if ($CertificateThumbprint) {
    $nsisArguments += @("/DSIGNTOOL=$SignTool", "/DCERTIFICATE_THUMBPRINT=$CertificateThumbprint",
        "/DTIMESTAMP_URL=$TimestampUrl")
}
$nsisArguments += (Join-Path $PSScriptRoot '../installer/OpenNord.nsi')
Invoke-CheckedNative $MakeNsis $nsisArguments
if ($CertificateThumbprint) { Sign-ReleaseFile $installerPath }

$archivePath = Join-Path $outputPath 'OpenNord-windows-x64.zip'
Compress-Archive -Path (Join-Path $stagePath '*') -DestinationPath $archivePath -Force
@($installerPath, $archivePath) | ForEach-Object {
    '{0}  {1}' -f (Get-FileHash -LiteralPath $_ -Algorithm SHA256).Hash.ToLowerInvariant(), [IO.Path]::GetFileName($_)
} | Set-Content -LiteralPath (Join-Path $outputPath 'SHA256SUMS.txt') -Encoding utf8NoBOM
Write-Host "Packages and SHA-256 checksums written to $outputPath"
